import { describe, expect, it } from "vitest";
import snapshot from "@/content/app-facts.json";
import { comparison, faq, MAX_FREE_ACCOUNTS, pricing, tiers } from "@/content/pricing";
import { site } from "@/content/home";

/**
 * This site's claims against the application's published contract.
 *
 * The application publishes `docs/product-facts.json` — generated from its
 * own constants and held to them by its own test — and
 * `src/content/app-facts.json` is a snapshot of it, refreshed by the
 * `sync-from-app` skill and never edited by hand.
 *
 * **That snapshot is what makes drift a CI failure rather than something
 * somebody notices.** Before it, every test here held the site to itself: the
 * price could agree with the comparison table and the FAQ and all three be
 * wrong together. Now the numbers have an external referent that travels with
 * the repository, so a claim can be checked without a network and without
 * anybody remembering to look.
 *
 * What it cannot do is notice that the *application* moved. That is the
 * skill's job, and the snapshot records which commit it last agreed with so
 * the question has an answer.
 */

const facts = snapshot.facts;
const free = facts.derived.plans.free;
const paid = facts.derived.plans.plus;

describe("the snapshot itself", () => {
  it("records where it came from, so the question 'is this current' is answerable", () => {
    expect(snapshot.source.repository).toBe("https://github.com/thtmnisamnstr/simple-balance");
    expect(snapshot.source.commit).toMatch(/^[0-9a-f]{40}$/);
    expect(snapshot.source.ref.length).toBeGreaterThan(0);
  });

  it("is the application's file, not something rewritten on the way in", () => {
    // If the generated marker is gone, somebody edited it by hand and the
    // referent is no longer external.
    expect(JSON.stringify(facts)).toContain("Generated by scripts/build-product-facts.mjs");
  });
});

/**
 * Rows are found by `id`, never by their visible label.
 *
 * The first version of the checks below looked for the row called "Financial
 * accounts". Rewording that label for a general reader turned all three
 * lookups into `undefined`, and `undefined` is not what any of them assert,
 * so they failed loudly — but a check comparing the application's enforced
 * limit against this page must fail because the *number* moved, not because
 * somebody edited a heading. `id` is the part that means the row rather than
 * the part that says it.
 */
const row = (id: string) => comparison.find((r) => r.id === id);

describe("what this site claims about plans", () => {
  it("has the rows these claims are about", () => {
    // Without this, a renamed id makes every lookup below return undefined
    // and each assertion fails for a reason that hides the real one.
    expect(row("accounts"), "no row with id 'accounts'").toBeDefined();
    expect(row("ads"), "no row with id 'ads'").toBeDefined();
  });

  it("uses the free account limit the application enforces", () => {
    expect(MAX_FREE_ACCOUNTS).toBe(free.accountLimit);
    expect(row("accounts")?.free).toBe(String(free.accountLimit));
  });

  it("calls the paid plan what the application calls it", () => {
    // The failure this whole mechanism exists for: the app said "Plus" while
    // this site said "Premium", and nothing could see both.
    const paidTier = tiers.find((t) => t.key === "premium");
    expect(paidTier?.name).toBe(paid.label);
  });

  it("calls the free plan what the application calls it", () => {
    expect(tiers.find((t) => t.key === "free")?.name).toBe(free.label);
  });

  it("gives the paid plan no account limit, as the application does", () => {
    expect(paid.accountLimit).toBeNull();
    expect(row("accounts")?.premium).toBe("Unlimited");
  });

  it("shows ads on exactly the plan the application shows them on", () => {
    expect(free.advertising).toBe(true);
    expect(paid.advertising).toBe(false);
    const ads = row("ads");
    expect(ads?.free).toBe("Yes");
    expect(ads?.premium).toBe("None");
  });
});

describe("what this site claims about price", () => {
  it("prints the yearly and monthly prices the application declares", () => {
    const yearly = Number(facts.declared.prices.yearly);
    const monthly = Number(facts.declared.prices.monthly);
    const paidTier = tiers.find((t) => t.key === "premium")!;

    // "$20" and "a year, or $2 a month" — the figures, not the phrasing.
    expect(paidTier.price).toContain(String(yearly));
    expect(paidTier.priceNote).toContain(String(monthly));
  });

  it("agrees with the terms page, which quotes the same two figures", () => {
    // A price is in four places on this site. Three of them are prose.
    expect(pricing.note.toLowerCase()).toContain("us dollars");
    expect(facts.declared.prices.currency).toBe("USD");
  });
});

describe("what this site claims the paid plan adds", () => {
  it("adds only what the application says it adds", () => {
    // The product's position: Premium raises a limit and removes ads. A
    // third thing here would be a capability held back from the free plan,
    // which is a different product from the one the application ships.
    expect(facts.declared.paidPlanAdds).toHaveLength(2);
    // Excluded by id, for the reason the helper above exists: the label on
    // that row is copy and changed with the rewrite, and an exclusion keyed
    // to a label that no longer exists is an exclusion that stops excluding.
    const heldBack = comparison.filter(
      (r) => r.free === false && r.premium === true && r.id !== "own-hardware",
    );
    expect(heldBack.map((r) => r.id)).toEqual([]);
  });

  it("claims no capability the application does not publish", () => {
    // Loose on purpose: the table's wording is marketing and the contract's
    // is description, so this checks the *count* has not run away from what
    // the application says it does, not that the sentences match.
    expect(facts.declared.capabilities.length).toBeGreaterThan(10);
    expect(comparison.length).toBeLessThanOrEqual(facts.declared.capabilities.length + 6);
  });
});

describe("the FAQ", () => {
  it("quotes the same limit as everything else", () => {
    const about = faq.find((f) => f.q.toLowerCase().includes("more than three"));
    expect(about, "the FAQ answers the over-limit question").toBeTruthy();
    expect(String(free.accountLimit)).toBe("3");
  });

  it("points at the application this site is about", () => {
    expect(site.sourceUrl).toBe(snapshot.source.repository);
  });
});
